# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockplot',
            old_name='caption',
            new_name='title',
        ),
    ]
