# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='report',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='report.Stock'),
        ),
    ]
