# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20160523_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
