# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20160523_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='end date')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('edit_date', models.DateTimeField(auto_now_add=True, verbose_name='date edited')),
                ('plotly_url', models.URLField(editable=False)),
                ('plotly_filename', models.CharField(editable=False, max_length=200)),
                ('plot_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Stock')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='plotly_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='stocks',
        ),
        migrations.AddField(
            model_name='report',
            name='stock_plots',
            field=models.ManyToManyField(blank=True, to='report.StockPlot'),
        ),
    ]
