# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20160524_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='default_plot',
            field=models.ManyToManyField(to='report.StockPlot'),
        ),
    ]
