# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200)),
                ('stock_plots', models.ManyToManyField(blank=True, to='stock.StockPlot')),
            ],
        ),
    ]
