# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='end date')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('edit_date', models.DateTimeField(auto_now_add=True, verbose_name='date edited')),
                ('plotly_url', models.URLField(editable=False)),
                ('plotly_filename', models.CharField(editable=False, max_length=200)),
                ('plot_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='default_plot',
            field=models.ManyToManyField(to='stock.StockPlot'),
        ),
    ]
